### ISSUE TITLE
how to recognize expression using AUs

### ISSUE THREAD

**Issue by Jingxia-Zhao** [machanic/AU_R-CNN#10]
Sorry to trouble you.I 'd like to know about how to recognize expression when detected the AUs,thank you.

**Comment by machanic** [comment]
@Jingxia-Zhao According to https://en.wikipedia.org/wiki/Facial_Action_Coding_System

Emotion | Action units
-- | --
Anger | 4+5+7+23
Contempt | R12A+R14A
Disgust | 9+15+16
Fear | 1+2+4+5+7+20+26
Happiness | 6+12
Sadness | 1+4+15
Surprise | 1+2+5B+26

**Comment by machanic** [comment]
@Jingxia-Zhao Also ,you can look at this page https://imotions.com/blog/facial-action-coding-system/
for how AUs look in face.
