### ISSUE TITLE
the package cannot be installed

### ISSUE THREAD

**Issue by wlzhao** [machanic/AU_R-CNN#11]
I installed all the required python packages.
Then I tried to install AU R-CNN by 'python setup.py install' under the folder, it reported the following error

cpdef double get_value(self, int y1, int y2, np.ndarray[DTYPE_float_t, ndim=1] weight) except? -1:
Invalid type 'DTYPE_float_t' at graph_learning/model/open_crf/cython/factor_graph.pyx:19:73

I did all my thing under Unbuntu 16.04 Thank you in advance!

**Comment by machanic** [comment]
@wlzhao This setup.py is not used to install AU R-CNN, it is used to install cython's CRF model, which is another method that uses the graph learning in my paper's experiment `CRF` section.

**Comment by machanic** [comment]
@wlzhao If you have already installed the packages, then you can use AU_rcnn/train.py
