### ISSUE TITLE
where could I find the mean_rgb.npy file

### ISSUE THREAD

**Issue by wlzhao** [machanic/AU_R-CNN#12]
Hello,

      In the case that I do not have dataset BP4D, is it possible for me to have this file 'mean_rgb.npy'?Could I run the demo without the support of dataset BP4D or dataset DISFA? I just use the pretrained model.

Thanks!

**Comment by machanic** [comment]
The README file in this project already wrote:
`
 **Training Necessary Files**

All training necessary files can be downloaded from https://drive.google.com/open?id=1y-yjOPuo7OcXA_bbNIZ0bfmV72mOBXON. I have also uploaded these files (~1.3G) into https://github.com/sharpstill/AU_R-CNN/tree/master/necessary_train_files_for_AU_R-CNN, so git clone to download this repository may be time expensive.
`
Please read the repo's readme first.
