### ISSUE TITLE
pickled data error

### ISSUE THREAD

**Issue by Mahdidrm** [machanic/AU_R-CNN#20]
Hi @machanic  
I really like this code and hope to have its Pytorch version.
Actually, I couldn't run it yet! I changed the addresses in config.py but I have errors on the needs!
like this one that drove me crazy :))

```
  File "D:\XAI\Code\AU_R-CNN-master\AU_rcnn\train.py", line 459, in <module>
    main()

  File "D:\XAI\Code\AU_R-CNN-master\AU_rcnn\train.py", line 202, in main
    extract_len=args.extract_len)  # 可改为/home/nco/face_expr/result/snapshot_model.npz

  File "D:/XAI/Code/AU_R-CNN-master\AU_rcnn\links\model\faster_rcnn\faster_rcnn_resnet101.py", line 119, in __init__
    mean_array = np.load(mean_file)

  File "C:\ProgramData\Anaconda3\envs\R-CNN\lib\site-packages\numpy\lib\npyio.py", line 444, in load
    raise ValueError("Cannot load file containing pickled data "

ValueError: Cannot load file containing pickled data when allow_pickle=False
```

Could you please guide me?

thanks

**Comment by machanic** [comment]
Please put put the mean file into the hard disk. You can download the **mean file** (which includes the value of mean of all pixels colors of images) from :  https://drive.google.com/open?id=1y-yjOPuo7OcXA_bbNIZ0bfmV72mOBXON

Then you can use `--mean` to specify the location of hard disk. 
https://github.com/machanic/AU_R-CNN/blob/master/AU_rcnn/train.py#L129

**Comment by machanic** [comment]
Also, you can refer to https://github.com/machanic/AU_R-CNN/issues/18 for more information about mean file.
