### ISSUE TITLE
Data Partition List

### ISSUE THREAD

**Issue by carltaddybearzz** [machanic/AU_R-CNN#3]
First of all, thanks for sharing your code!!
I have a question about the data list you provided.  For BP4D, is the subjects partition same as DRML which detailed [here](https://github.com/BCV-Uniandes/AUNets)? You are not using the data list provided [here](https://github.com/wiibrew/EAC-Net), right? Since the later one seems to be unbalanced for different folds. 
BTW, according to the results from your paper and [this one](https://github.com/BCV-Uniandes/AUNets), pre-trained VGG and ResNet can actually achieve ~60 F1 on [BP4D, same partition, frame based detections], which is consistent with my experiments. Originally I thought there were some issues with my implementations since those baselines seem to be as good as some latest conference papers.

**Comment by sharpstill** [comment]
@carltaddybearzz 1. I have uploaded my 3-fold data partition into [https://github.com/sharpstill/AU_R-CNN/tree/master/necessary_train_files_for_AU_R-CNN/BP4D_3_fold](https://github.com/sharpstill/AU_R-CNN/tree/master/necessary_train_files_for_AU_R-CNN/BP4D_3_fold) and [https://github.com/sharpstill/AU_R-CNN/tree/master/necessary_train_files_for_AU_R-CNN/DISFA_3_fold](https://github.com/sharpstill/AU_R-CNN/tree/master/necessary_train_files_for_AU_R-CNN/DISFA_3_fold)

2. Yes, you can check my paper results.
Furthermore, I have uploaded all the training necessary files onto [https://github.com/sharpstill/AU_R-CNN/tree/master/necessary_train_files_for_AU_R-CNN](https://github.com/sharpstill/AU_R-CNN/tree/master/necessary_train_files_for_AU_R-CNN)

**Comment by machanic** [comment]
Closing now
